changeSet:
  id: 4-create-table-product-categories
  author: Your Name
  changes:
    - createTable:
        tableName: product_categories
        columns:
          - column:
              name: id
              type: uuid
              constraints:
                primaryKey: true
                nullable: false
          - column:
              name: product_id
              type: uuid
              constraints:
                nullable: false
          - column:
              name: category_id
              type: uuid
              constraints:
                nullable: false
          - addForeignKeyConstraint:
              baseTableName: product_categories
              constraintName: fk_product_categories_product_id
              referencedTableName: products
              referencedColumnNames:
                - id
              columns:
                - column:
                    name: product_id
                    type: uuid
              onDelete: CASCADE
          - addForeignKeyConstraint:
              baseTableName: product_categories
              constraintName: fk_product_categories_category_id
              referencedTableName: categories
              referencedColumnNames:
                - id
              columns:
                - column:
                    name: category_id
                    type: uuid
              onDelete: CASCADE
