version: '3.9'

services:
  db:
    container_name: postgres_dev
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pqadmin:
    container_name: pgadmin_dev
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    ports:
      - 5050:80
    env_file:
      - .env.development
    depends_on:
      - db
  app:
    container_name: app_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PORT: ${SERVICE_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DEPLOY_TYPE: docker
    env_file:
      - .env.development
    depends_on:
      - db

  liquibase:
    container_name: liquibase_dev
    image: liquibase/liquibase
    volumes:
      - ./changelogs:/liquibase/changelog
    depends_on:
      - db
    environment:
      - URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - USERNAME=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env.development
    command:
      - '--url=jdbc:postgresql://db:5432/${POSTGRES_DB}'
      - '--changeLogFile=/changelog/db.changelog-master.yaml'
      - '--username=${POSTGRES_USER}'
      - '--password=${POSTGRES_PASSWORD}'
      - 'update'
    networks:
      - default

volumes:
  db_data_dev:
    driver: local
  pgadmin_data_dev:
    driver: local
